import { NextPageContext } from "next";
import Head from "next/head";
import { getSession } from "next-auth/react";
import DashboardLayout from "~/layouts/DashboardLayout";
import { ReactElement } from "react";
import { NextPageWithLayout } from "~/components/util/LayoutTypes";
import { Grid } from "@mantine/core";

import { StatCard } from "~/components/dashboard/StatCard";
import { IconCalendar, IconCash, IconStar } from "@tabler/icons-react";

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Grid>
          <Grid.Col xl={3} lg={3} md={4} sm={6} xs={12}>
            <StatCard
              title="Appointments"
              caption="Compared to previous month"
              value="200"
              diff={5}
              icon={<IconCalendar />}
            />
          </Grid.Col>
          <Grid.Col xl={3} lg={3} md={4} sm={6} xs={12}>
            <StatCard
              title="Revenue"
              caption="Compared to previous month"
              value="$1,276"
              diff={34}
              icon={<IconCash />}
            />
          </Grid.Col>
          <Grid.Col xl={3} lg={3} md={4} sm={6} xs={12}>
            <StatCard
              title="Satisfaction"
              caption="Compared to previous month"
              value="4.8"
              diff={3}
              icon={<IconStar />}
            />
          </Grid.Col>
          <Grid.Col xl={3} lg={3} md={4} sm={6} xs={12}>
            <StatCard
              title="Cancelation"
              caption="Compared to previous month"
              value="3%"
              diff={-1}
              icon={<IconStar />}
            />
          </Grid.Col>
        </Grid>
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default Home;
