import { NextPageContext } from "next";
import Head from "next/head";
import { getSession } from "next-auth/react";
import DashboardLayout from "~/layouts/DashboardLayout";
import { ReactElement } from "react";
import { NextPageWithLayout } from "~/components/util/LayoutTypes";
import { Grid } from "@mantine/core";

import { ServiceList } from "~/components/services/ServiceList";

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}

const Services: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>DetailPad - Services</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Grid>
          <Grid.Col xl={12} lg={12} md={12} sm={12} xs={12}>
            <ServiceList />
          </Grid.Col>
        </Grid>
      </div>
    </>
  );
};

Services.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default Services;
