import { NextPageContext } from "next";
import Head from "next/head";
import { getSession } from "next-auth/react";
import DashboardLayout from "~/layouts/DashboardLayout";
import { ReactElement } from "react";
import { NextPageWithLayout } from "~/components/LayoutTypes";

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}

const Team: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Team</div>
    </>
  );
};

Team.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default Team;
